### ISSUE TITLE
Cannot install package

### ISSUE THREAD

**Issue by whositwhatnow** [dmi3kno/polite#37]
Hello is this still available?  I cannot install it and getting package not found on cran and wheni try to install from source I get an error ERROR: dependencies ‘here’, ‘ratelimitr’, ‘robotstxt’ are not available for package ‘polite’

**Comment by dmi3kno** [comment]
{polite} is on CRAN and installing. The package depends on the following packages
https://github.com/dmi3kno/polite/blob/15655f166b610f98ca563c98b045965119cc56a4/DESCRIPTION#L14-L22

Try restarting your R session and then install {polite} with
```r
install.packages("polite")
```
Otherwise, you could try installing the required packages first and then come back to installing {polite}
